# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f465b2b5ce8282201017c1c4b7181c1def79208352519a655f3ed8e10879ab3d97ff6af328765540509dfbf1c78d2d757d4624ab53a744e35caa6ce792ca3c28

test:
  secret_key_base: d406bea1317eedc89a0c40b82263335ced787bf6c067bdb9034915f623ced25b8bdbc8c223d7f391bffd798f2520adce4fc0d6cdccd26943237762e40aba8571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
